
INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('UNFRIENDED', 'Fantascienza, Azione', 'https://www.youtube.com/embed/y-_8WhoQbS8', 90, 'Durante una video chat notturna, sei amici del liceo ricevono un messaggio di Skype da una compagna di classe che si è uccisa esattamente un anno prima. Inizialmente pensano che si tratti di uno scherzo, ma poi si rendono conto che hanno a che fare con qualcosa che non fa parte di questo mondo, qualcosa che li vuole morti.', 'http://mr.comingsoon.it/imgdb/locandine/big/50967.jpg', 'Levan Gabriadze', 'USA', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('TED 2 – IL FILM', 'Commedia', 'https://www.youtube.com/embed/sQKmZMv3qVU', 90, 'Seth MacFarlane ritorna come sceneggiatore, regista e voce protagonista di Ted 2, il sequel prodotto da Universal Pictures e Media Rights Capital della irriverente commedia di maggior successo di tutti i tempi. Se nel primo film abbiamo visto Ted ubriacarsi, ballare, andare in televisione e fare sesso… ora cosa potrà mai succedere?', 'http://mr.comingsoon.it/imgdb/locandine/big/50941.jpg', 'Seth MacFarlane', 'usa', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('TERMINATOR GENISYS 3D', 'Azione', 'https://www.youtube.com/embed/javqj8YzTWk', 126, 'Quando John Connor, leader della resistenza umana spedisce il sergente Kyle Reese indietro nel 1984 per proteggere Sara Connor e per salvaguardare il futuro, un evento inaspettato crea una frattura nella linea temporale. Il sergente Reese si troverà in una nuova e sconosciuta versione del passato, dove si troverà di fronte ad improbabili alleati, tra cui il Guardiano, nuovi pericolosi nemici, e una nuova missione inaspettata: Un nuovo futuro …', 'http://mr.comingsoon.it/imgdb/locandine/big/50400.jpg', 'Alan Taylor', 'USA', 2015, "3D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('PIXELS 3D', 'Azione', 'https://www.youtube.com/embed/kCJwDMAO72s', 100, 'Una razza aliena scambia le immagini dei vecchi videogames per una dichiarazione di guerra e attacca la terra usando i giochi stessi come modelli per i loro assalti. Il Presidente degli Stati Uniti chiama allora il suo amico d''infanzia Sam Brenner (Adam Sandler), un campione di videogames negli anni ''80, per difendere la terra. Il destino del nostro pianeta è nelle mani di un improbabile team di nostalgici giocatori.', 'http://mr.comingsoon.it/imgdb/locandine/big/50612.jpg', 'Chris Columbus', 'USA', 2015, "3D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('MISSION: IMPOSSIBLE: ROGUE NATION', 'Azione', 'https://www.youtube.com/embed/EWC9JZtMOWQ', 245, 'Ethan e il suo team affrontano la loro nuova missione impossibile, la più dura finora: eliminare il Sindacato, un''organizzazione criminale internazionale, altamente addestrata come loro e incaricata di distruggere la IMF.', 'http://mr.comingsoon.it/imgdb/locandine/big/51139.jpg', 'Christopher McQuarrie', 'usa', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Star Wars: Il Risveglio della Forza', 'Fantascienza, Azione', 'https://www.youtube.com/embed/wCc2v7izk8w', 150, 'Prosegue la saga creata da George Lucas a trenta anni da "Il ritorno dello Jedi".', 'http://mr.comingsoon.it/imgdb/locandine/big/49611.jpg', 'J.J. Abrams', 'usa', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('JURASSIC WORLD 3D', 'Azione', 'https://www.youtube.com/embed/Mgv1X7DOqK0', 125, 'Sono passati ventidue anni e Isla Nublar si popola nuovamente; la lussureggiante isola ospiterà finalmente, come John Hammond aveva a suo tempo progettato, un parco per famiglie a tema dinosauri: la notorietà del parco inizia però presto a diminuire, così come le sue visite. Per risolvere il problema, i proprietari decidono di aprire una nuova, grandiosa attrazione. Ma tra le minacciose ombre dell''Isla Nublar, l''imprevisto è in agguato…', 'http://mr.comingsoon.it/imgdb/locandine/big/49556.jpg', 'Colin Trevorrow', 'USA', 2015, "3D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Lo hobbit: la battaglia delle cinque armate', 'Fantastico, epico, avventura', 'https://www.youtube.com/embed/g8NUYHhfuxc''', 144, 'Lo Hobbit la Battaglia delle Cinque Armate porta la conclusione delle avventure di Bilbo Baggins, Thorin Scudodiquercia e la Compagnia di Nani. Dopo aver reclamato la loro patria dal drago Smaug, la compagnia ha involontariamente scatenato una forza letale nel mondo. Infuriato, Smaug abbatte la sua ira ardente e senza pietà alcuna su uomini inermi, donne e bambini di Pontelagolungo. Ossessionato soprattutto dal recupero del suo tesoro, Thorin sacrifica l''''onore e mentre i frenetici tentativi di Bilbo di farlo ragionare si accumulano finiscono per guidare lo Hobbit verso una scelta disperata e pericolosa.', 'http://www.hobbitfilm.it/wp-content/uploads/2014/10/hobbit_the_battle_of_the_five_armies_ver21_xxlg.jpg', 'Peter Jackson', 'usa', 2014, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('The wolf of wall street', 'Biografico, Drammatico, Commedia nera', 'https://www.youtube.com/embed/iszwuX1AK6A', 180, 'Ripercorre la storia di un giovane broker americano, Jordan Belfort, che negli anni Novanta, a soli 26 anni, è riuscito a scalare le vette del successo nel mondo della finanza, arrivando a guadagnare cifre esorbitanti che gli hanno permesso di vivere nel lusso più sfrenato. Adottando il motto “Non c''è nobiltà nella povertà”, Jordan si guadagna il nome di “Lupo di Wall Street”. Diventa abilissimo nel truffare il prossimo, quei piccoli investitori ignari che ancor oggi ne pagano le conseguenze. A New York fonda la “Stratton Oakmont”, la sua agenzia , che in realtà altro non è che un centro dove avviare investimenti illeciti. Ben presto però diventa schiavo della droga. Inizia così la lunga spirale che lo trascinerà sempre più in basso, aprendo una voragine nel suo essere uomo, e che lo condurrà ad una progressiva perdita della ragione, fino a rischiare la morte.', 'http://pad.mymovies.it/filmclub/2010/07/050/locandina.jpg', 'Martin Scorsese', 'usa', 2013, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Big hero 6', 'animazione, azione, commedia, fantascienza', 'https://www.youtube.com/embed/DlLHLlk84cg', 102, 'Il primo film d''animazione della Marvel, creato dai Walt Disney Studios, racconta di una squadra di supereroi. Quando il governo giapponese ha voluto una squadra di supereroi a sua disposizione, un gruppo super segreto di politici e uomini d''affari, aka il Giri, è stato formato per reclutare e allenare potenziali agenti super umani per la squadra Big Heo 6.', 'http://bayanbox.ir/view/8042506921113343798/Big-Hero-6.jpg', 'Don Hall, Chris Williams', 'usa', 2014, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Kingsman: Secret Service', 'Azione, Thriller', 'https://www.youtube.com/embed/7XJpZFsLIGw', 129, 'L''agente Lancillotto perde la vita durante una missione di guerra e il suo capo, Galahad, non si perdona e offre al figlio piccolo del compagno scomparso una medaglia e un numero di telefono. Diciassette anni dopo quel bambino è un ragazzo, Eggsy, che si è messo nei guai con dei delinquenti del quartiere. Comporrà quel numero di telefono e si ritroverà davanti Galahad in persona, alias Harry Hart, pronto ad offrirgli l''occasione di una nuova vita. Una vita da spia. Una vita da Kingsman. ', 'http://mr.comingsoon.it/imgdb/locandine/big/50192.jpg', 'Matthew Vaughn', 'usa', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('American Ultra', 'Azione, Commedia', 'https://www.youtube.com/embed/o4TEj8oj2Lw', 110, 'Il film racconta la storia di Mike, un drogato ormai privo di motivazioni (Jesse Eisenberg), che vive con la sua fidanzata (Kristen Stewart) in una piccola e sonnolenta cittadina. Una notte le loro vite subiscono una svolta inattesa quando il passato di Mike torna a tormentarlo: diventerà l''obiettivo di un''operazione governativa per farlo fuori.', 'http://mr.comingsoon.it/imgdb/locandine/big/50937.jpg', 'Nima Nourizadeh', 'usa', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Lego Movie', 'Azione, Animazione, Commedia', 'https://www.youtube.com/embed/jtlG3ywRPQ4', 100, 'Il film d''animazione digitale in 3D segue le avventure di Emmet, un pupazzo LEGO ordinario, ligio alle regole, e del tutto comune che viene erroneamente identificato come una persona dai poteri straordinari, la figura chiave per salvare il mondo. Viene quindi coinvolto da un gruppo di sconosciuti, in una missione epica nel tentativo di fermare un tiranno malvagio, un''avventura senza speranza per Emmet, che lo coglie decisamente impreparato.', 'http://mr.comingsoon.it/imgdb/locandine/big/49795.jpg', 'Phil Lord, Christopher Miller', 'usa', 2014, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Fury', 'Drammatico, Guerra', 'https://www.youtube.com/embed/-lhgVFSmw7w', 145, 'Nell''aprile del 1945, mentre gli Alleati sferrano l''attacco decisivo in Europa, un agguerrito sergente, Wardaddy, comanda un carro armato Sherman e il suo equipaggio di cinque uomini in una missione mortale dietro le linee nemiche. In inferiorità numerica e disarmato, Wardaddy e i suoi uomini saranno protagonisti di gesta eroiche per colpire al cuore la Germania nazista.', 'http://mr.comingsoon.it/imgdb/locandine/big/50045.jpg', 'David Ayer', 'USA', 2014, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Humandroid', 'Azione, Fantascienza', 'https://www.youtube.com/embed/Ly02_jcS8xY', 120, 'Ogni bimbo viene al mondo pieno di promesse e nessuno più di Chappie: lui è un talento, è speciale, un prodigio. Come ogni bambino, Chappie verrà influenzato dagli ambienti che lo circondano – alcuni buoni, altri meno – affidandosi al cuore ed all''anima per trovare la sua strada nel mondo e diventare un uomo. Ma c''è una cosa che rende Chappie diverso da chiunque altro: è un robot. Il primo ed unico robot in grado di pensare ed avere sentimenti.', 'http://mr.comingsoon.it/imgdb/locandine/big/50269.jpg', 'Neill Blomkamp', 'usa', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Spectre', 'Spionaggio, Azione', 'https://www.youtube.com/embed/jN1JF7zVcRk', 120, 'Arriva nelle sale un altro adrenalinico episodio della saga più popolare della storia del cinema. Per la quarta volta Daniel Craig sarà James Bond al fianco di Ralph Fiennes, Naomie Harris e Ben Whishaw. Un messaggio criptico dal passato di Bond porta l''agente 007 a seguire una pista per smascherare una minacciosa organizzazione. Mentre M lotta contro le forze politiche per tenere in vita i servizi segreti, Bond tenterà di aggirare numerosi inganni e svelare la terribile verità che si cela dietro Spectre.', 'http://mr.comingsoon.it/imgdb/locandine/big/50447.jpg', 'Sam Mendes', 'usa', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Avengers: Age of Ultron', 'Azione, Fantascenza', 'https://www.youtube.com/embed/5xIdeeTKXcI', 141, 'Quando Tony Stark tenta di avviare un progetto dormiente per il mantenimento della pace, le cose vanno male e gli eroi più potenti della Terra – Iron Man, Captain America, Thor, L''Incredibile Hulk, Vedova Nera e Occhio di Falco – devono affrontare la prova più ardua di sempre, mentre il destino del pianeta è in bilico. Quando il misterioso Ultron emerge dall''ombra, la squadra deve riunirsi per fermare un avversario terrificante e tecnologico deciso a sterminare l''umanità. Lungo il cammino, incontreranno due individui potenti e misteriosi, Wanda Maximoff e Pietro Maximoff, e un vecchio amico dotato di un nuovo aspetto, chiamato Visione.', 'http://mr.comingsoon.it/imgdb/locandine/big/49238.jpg', 'Joss Whedon', 'usa', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Tomorrowland - Il mondo di domani', 'Fantascenza', 'https://www.youtube.com/embed/YnB9__lltKM', 130, 'Il film racconta la storia di Frank (George Clooney), un ex enfant prodige ormai disilluso, e Casey (Britt Robertson), un''adolescente ottimista e intelligente che trabocca di curiosità scientifica. Legati da un destino comune, i due intraprendono una pericolosa missione insieme, per svelare i segreti di una misteriosa dimensione spazio-temporale nota come “Tomorrowland”. Le loro imprese cambieranno sia il mondo che la propria vita, per sempre.', 'http://mr.comingsoon.it/imgdb/locandine/big/49630.jpg', 'Brad Bird', 'usa', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Deadpool', 'Azione, Commedia', 'https://www.youtube.com/embed/FyKWUTwSYAs', 121, 'Basato su uno dei più anticonformisti degli anti-eroi della Marvel, Deadpool racconta le origini di Wade Wilson, ex membro delle Forze Speciali diventato mercenario, il quale, dopo essere stato sottoposto a un esperimento non autorizzato che gli conferisci, tra gli altri, il potere di guarigione veloce, decide di creare il suo alter ego Deadpool. Dotato di nuove capacità e di un macabro senso dell''umorismo, Deadpool inizia la caccia all''uomo che ha quasi distrutto la sua vita.', 'http://mr.comingsoon.it/imgdb/locandine/big/47827.jpg', 'Tim Miller', 'usa', 2016, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Fantastici 4', 'Azione, Avventura, Sci-Fi', 'https://www.youtube.com/embed/JGISnrMKBfo', 100, 'I Fantastici Quattro, moderna re-interpretazione del team di supereroi più longevo della Marvel, è la storia di quattro giovani che vengono teletrasportati in un pericoloso universo alternativo, che altera la loro forma fisica in un modo sconvolgente. Le loro vite vengono inequivocabilmente stravolte, il team dovrà imparare a controllare le loro nuove abilità e a lavorare insieme per salvare la Terra da un loro vecchio amico diventato nemico.', 'http://mr.comingsoon.it/imgdb/locandine/235x336/50204.jpg', 'Josh Trank', 'usa', 2015, "2D");

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Transformers 4 l''Era dell''Estinzione', 'avventura,azione,fantascientifico', 'https://www.youtube.com/embed/LKVS0xPM80o', 165, '“Transformers 4” comincia subito dopo la fine di “Transformers 3”, quando una grande battaglia aveva lasciato una città a pezzi. L''umanità si è ricomposta, Autobot e Decepticon sono quasi spariti dal pianeta. Un gruppo di potenti e ingegnosi uomini d''affari e scienziati tenta di imparare dalle passate incursioni dei robot spingendosi oltre i limiti controllabili della tecnologia - tutto questo mentre un''antica e potente minaccia Transformer prende di mira la Terra. L''epica avventura e battaglia tra bene e male, libertà e schiavitù ricomincia.', 'http://mr.comingsoon.it/imgdb/locandine/big/49355.jpg', 'Micheal Bay', 'usa', 2014);

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Minions 3D', 'Animazione', 'https://www.youtube.com/embed/wA1sjzkvzko', 100, 'La storia di Minions di Universal Pictures e Illumination Entertainment inizia all''alba dei tempi. Partendo da organismi gialli unicellulari, i Minion si evolvono attraverso i secoli, perennemente al servizio del più spregevole dei padroni.', 'http://mr.comingsoon.it/imgdb/locandine/big/50890.jpg', 'Kyle Balda, Pierre Coffin', 'usa', 2015);

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Mad Max: Fury Road', 'Azione', 'https://www.youtube.com/embed/gBZlfbCnUOE', 120, 'Poco dopo aver vendicato la morte di sua moglie e di suo figlio, Max Rockatansky ha lasciato l''Mfp, il corpo di polizia di cui era membro, e si è messo in proprio. Il mondo, intanto, è all''indomani della crisi conseguente alla guerra globale che l''ha devastato. Non possedendo più nulla tranne il suo veicolo, la Pursuit Special, Max ora deve imparare a sopravvivere in lande post-apocalittiche, affrontando i feroci e spietati guerrieri che le abitano.', 'http://mr.comingsoon.it/imgdb/locandine/big/47814.jpg', 'George Miller', 'usa', 2015);

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Fast & Furious 7', 'Azione, Motori', 'https://www.youtube.com/embed/-ulmNKshZsI', 140, 'Fast & Furious 7 riprende la storia della squadra di Dom (Diesel) e Brian (Walker) a distanza di un anno dal loro ritorno negli Stati Uniti con tanto di scuse. Nel frattempo sono passati ad una vita ligia alle regole, e la casa ha assunto un tono surreale. Dom cerca disperatamente di riavvicinarsi a Letty (Rodriguez), mentre Brian lotta per ambientarsi alla vita di periferia con Mia (Brewster) e il loro figlio, mentre Tej (Bridges) e Roman (Gibson) celebrano la loro libertà inseguendo il loro sogno di playboy. All''insaputa di tutti però il pericolo è alle porte, sottoforma di un sanguinario killer delle forze speciali inglesi, che rivendica un conto in sospeso.', 'http://mr.comingsoon.it/imgdb/locandine/big/49946.jpg', 'James Wan', 'usa', 2015);

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Lucy', 'azione, fantascienza, thriller', 'https://www.youtube.com/embed/tsR2-v554Hs', 90, 'Lucy è una studentessa che vive a Taiwan. Si trova costretta a consegnare una valigetta dal contenuto misterioso a un criminale coreano, Mr. Jang. Costui, una volta verificato ciò che gli è stato portato, sequestra la ragazza. Le fa inserire nel corpo uno dei pacchetti ricevuti che contiene una sostanza di cui dovrebbe essere la passiva trasportatrice. Non sarà così perché il pacchetto si rompe e il prodotto chimico viene assorbito dal suo corpo il quale progressivamente sviluppa una capacità di conoscenza e di potere inimmaginabili per chi non sia, come il professor Norman, un neuro ricercatore.', 'http://mr.comingsoon.it/imgdb/locandine/big/50417.jpg', 'Luc Besson', 'Usa, Fancia', 2014);

INSERT INTO "public".film (titolo, genere, link_trailer, durata, descrizione, locandina, regia, nazionalita, anno, tipo) 
	VALUES ('Guardiani della galassia', 'azione, fantascienza, supereroi', 'https://www.youtube.com/embed/PYcgR4iP8r8', 122, 'Peter Quill è un audace avventuriero dello spazio che si fa chiamare Spacelord e va a zonzo su una nave lercia, dove ascolta sempre e soltanto la musicassetta che aveva con sé quel fatidico giorno del 1988. Entrato per caso in possesso di una sfera misteriosa, Quill scopre che il feroce Ronan è determinato ad averla per distruggere il pianeta Xandar e molto probabilmente non solo quello. Per sventare il piano apocalittico di Ronan, Peter si allea quindi con una squadra di ricercati come lui: il procione Rocket, mago della meccanica, il suo amico Groot, una creatura dalle sembianze d''albero, la bella e dannata Gamora e il grosso Drax, assetato di vendetta.', 'http://mr.comingsoon.it/imgdb/locandine/big/49179.jpg', 'James Gunn.', 'usa', 2014);
